### ISSUE TITLE
Setup the association's address

### ISSUE THREAD

**Issue by href** [python-summit/SPSA#1]
The association needs to get an address and as mentioned by @andrekeller the Post has a nifty little service for just this use case: https://www.post.ch/de/geschaeftlich/themen-a-z/preise-empfangen/preise-postempfang/preise-vereinsadressen

The 20.- a year seem reasonable to me.

To do this we need to fill out a form. The mail will then be forwarded to the secretary, i.e. me.

I think I should do this, as the Post form asks for a single committee member's signature. But since our bylaws say that the president and someone from the committee has to sign, unless the committee delegates this. So it is my understanding that we need a committee meeting to set this up.

Unless I'm wrong about having to convene a meeting, this would be an item on the agenda for the our first such meeting.

**Comment by href** [comment]
Moved to https://github.com/SwissPy/SPSA/issues/1

**Comment by href** [comment]
I have sent the application for the address by e-mail on the weekend but I have not heard back yet.

**Comment by The-Compiler** [comment]
What's the state of this?

**Comment by href** [comment]
It's been setup. The address is:

Swiss Python Summit Association
8000 Zürich

Thanks for the ping!
