### ISSUE TITLE
Setup the association's bank account

### ISSUE THREAD

**Issue by href** [python-summit/SPSA#2]
Copied from https://github.com/SwissPy/sps17/issues/3

---

I just see a problem with Bank Linth because it is a local bank (https://www.banklinth.ch/de/privatkunden/kontakt/standortfinder)

**Since we are a Swiss (as opposed to Cantonal) association, we should better find a Bank which is easily accessible in the whole country** (and this excludes Cantonal Banks and Reiffeisen banks). 

I have looked at the PostFinance offer for associations (https://www.postfinance.ch/en/biz/prod/acc/club/detail.html), :
- 60 CHF/year fees (which we can easily cover with the membership fees)
- two bancomat cards included,
- e-banking,
- desks granularly located in the whole country,
- to open the account, President + one  comittee member must go to a PostFinance desk with the documentation and identity cards.
- bylaws in english accepted

Called UBS Neuchâtel to get some info: as soon as they understood we are a making up a small association they put me on hold. After five minutes of waiting I decided to quit. (and I did not manage to gather information about "Associations Accounts" on UBS or Credit Suisse on their internet sites)

ABS likes associations (https://www.abs.ch/de/online-schalter/eroeffnen-beantragen/konto-eroeffnen/einlagekonto-eroeffnen/):
- 36 CHF/year
- e-banking,
- desks in Lausanne, Olten, Zurich, Geneva,
- cards?
- apparently the opening of the account may be handled by mail
- **only bylaws in a swiss official language**

Credit Suisse:
- 60 CHF/year
- e-banking
- no cards included (50 CHF/year/card)
- bylaws in english not a problem, but they want to inspect the bylaws before accepting,
- account can be managed at any desk in Switzerland

**Comment by The-Compiler** [comment]
With ABS, seems like a card is [30 CHF per year](https://www.abs.ch/de/firmen-institutionen/fuer-den-zahlungsverkehr/abs-maestro-karte/#konditionen-und-gebuehren) per card, and 3 CHF per transaction after the 10th transaction per month.

**Comment by dbrgn** [comment]
> and 3 CHF per transaction after the 10th transaction per month.

That's only for getting cash at the ATM. Maestro payments can be done for free without limits. I don't think we need to get cash more than 10 times a month.

By the way, it does not matter what ATM you use, any ATM is fine.

The e-banking is OK, albeit a bit old-school. But browser-based (with [crontosign](https://www.cronto.com/crontosign-transaction-authentication-mobile.htm)).

**Comment by chiesax** [comment]
And what about if we need to put cash into an ABS account (for instance the tickets money)? I guess we need to go to the desk, right? Anyhow I am planning to call them this afternoon.

**Comment by dbrgn** [comment]
> And what about if we need to put cash into an ABS account (for instance the tickets money)? I guess we need to go to the desk, right?

Probably, yes. Or you keep the cash and pay the amount via ebanking from your private account.

**Comment by chiesax** [comment]
> Probably, yes. Or you keep the cash and pay the amount via ebanking from your private account.

If we decide to do it this way, then in principle we do not even need a card. But this is just 24 CHF/year difference with Postfinance...

**Comment by dbrgn** [comment]
There's also [Raiffeisen](https://www.raiffeisen.ch/raiffeisen/internet/home.nsf/WebPagesByTitleALL/66D6763C5459A043C1256F9A00555477), but I don't get whether the account is free or not. And it might be only for associations with an entry in the trade register.

Edit: According to [this source](http://www.moneyland.ch/de/raiffeisen/firmenkonto/vereinskonto) it might be free.

**Comment by chiesax** [comment]
True, but Raiffeisen is actually not a "Swiss" bank, but a galaxy of local banks. So for instance you cannot go to the desk of Raiffesen Rapperswil and get information about your account on Raiffeisen Mendrisio. 

It may be possible though to put money into Raiffesen A even if the account is on Raiffeisen B, so I will call them too...

**Comment by dbrgn** [comment]
> It may be possible though to put money into Raiffesen A even if the account is on Raiffeisen B, so I will call them too...

Yes, that should be possible. I think that's the point of grouping all local banks under the same name :)

**Comment by chiesax** [comment]
Whats funny is that bank secrecy applies between Raiffeisen banks (I tested it)...

**Comment by chiesax** [comment]
I have called ABS right now, but unfortunately they are not allowed (by FINMA) to handle bylaws in english... Apparently this is because they are not an "international" bank.

So another plus to Postfinance, which apparently is allowed to handle international stuff, but I shall call them again to check...

**Comment by chiesax** [comment]
So they confirmed me that Postfinance do not care if the bylaws are in english. They also explained me that cash can be (commited and ) pushed to the account at any post desk using the postfinance cards.

**Comment by dbrgn** [comment]
@chiesax your call. If you think they're well suited, go for it.

**Comment by chiesax** [comment]
Managed to get Credit Suisse, but they are more expensive than Postfinance (same price but no cards included). 

@SwissPy/orga: if nobody is against Postfinance, I think we should go for it!

**Comment by href** [comment]
I'm 👍 with Postfinance. I think it's a reasonable choice.

**Comment by ccdesales** [comment]
+1 PF

**Comment by chiesax** [comment]
Now all we need to do is to apply online for an association account: https://www.postfinance.ch/en/biz/prod/acc/club/apply.html . I did not apply yet since it is probably more reasonalbe that @href handles this, since he has all the documents?

**Comment by href** [comment]
Up to you. I can also send you the documents - I have them available as PDF.

**Comment by chiesax** [comment]
I have submitted the docs to Postfinance today. I hope we will soon get the account...

**Comment by The-Compiler** [comment]
We have a bank account by now, right?
