### ISSUE TITLE
Add society info to the homepage

### ISSUE THREAD

**Issue by href** [python-summit/SPSA#4]
We should add infos on what we do, our issue trackers (this one and the sps17 one), our contact info and how to join us. Anything else?

**Comment by chiesax** [comment]
- link to association documents
- info on how to become members (including fee)
- info on how to become sponsors

**Comment by dbrgn** [comment]
- info on what a membership means (helping to organize the conference)

**Comment by href** [comment]
I reworked the call for helpers page to include some information about the society:
http://www.python-summit.ch/pages/call-for-helpers.html

Basically dividing the helpers into one-day and long-term helpers. The sponsoring, once defined, should go to a separate page in my opinion.
